class TestData:
    BASE_URL = "https://parabank.parasoft.com/parabank/index.htm"
    USER_NAME = "bulbul"
    PASSWORD = "600600"
    TITLE = "ParaBank | Welcome | Online Banking"
    DTITLE = "ParaBank | Accounts Overview"

    """ REGISTRATION details"""
    REGISTERATION_URL = "https://parabank.parasoft.com/parabank/register.htm"
    # FIRSTNAME = "Ram"
    # LASTNAME = "Sam"
    # ADDRESS = "Ramsumsum"
    # CITY = "Ramsumsum"
    # STATE = "Ramsumsum"
    # ZIPCODE = "654012365"
    # PHONE = "9744518665"
    # SSN = "9840984084"
    # RUSERNAME = "nice6345d98"
    # PASSWORD2 = "654654"
